name: Run Nox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: wntrblm/nox@2024.04.15
        with:
          python-versions: "3.10, 3.11, 3.12, 3.13"
      - name: Run Test
        run: |
          nox -s test
