name: Run Nox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs_on: ubuntu-latest
    steps:
      - uses: wntrblm/nox
        with:
          python-versions: "2.7, 3.5, 3.11, pypy-3.9"
